// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/v1/game.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetQuizzes_FullMethodName      = "/user.v1.GameService/GetQuizzes"
	GameService_GetSessions_FullMethodName     = "/user.v1.GameService/GetSessions"
	GameService_JoinQuiz_FullMethodName        = "/user.v1.GameService/JoinQuiz"
	GameService_QuitQuiz_FullMethodName        = "/user.v1.GameService/QuitQuiz"
	GameService_CreateQuiz_FullMethodName      = "/user.v1.GameService/CreateQuiz"
	GameService_GetActiveQuiz_FullMethodName   = "/user.v1.GameService/GetActiveQuiz"
	GameService_AnswerQuestions_FullMethodName = "/user.v1.GameService/AnswerQuestions"
	GameService_StartRandomQuiz_FullMethodName = "/user.v1.GameService/StartRandomQuiz"
	GameService_StartGenreQuiz_FullMethodName  = "/user.v1.GameService/StartGenreQuiz"
	GameService_StartForYouQuiz_FullMethodName = "/user.v1.GameService/StartForYouQuiz"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	GetQuizzes(ctx context.Context, in *GetQuizzesRequest, opts ...grpc.CallOption) (*GetQuizzesResponse, error)
	GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error)
	JoinQuiz(ctx context.Context, in *JoinQuizRequest, opts ...grpc.CallOption) (*JoinQuizResponse, error)
	QuitQuiz(ctx context.Context, in *QuitQuizRequest, opts ...grpc.CallOption) (*QuitQuizResponse, error)
	CreateQuiz(ctx context.Context, in *CreateQuizRequest, opts ...grpc.CallOption) (*CreateQuizResponse, error)
	GetActiveQuiz(ctx context.Context, in *GetActiveQuizRequest, opts ...grpc.CallOption) (*GetActiveQuizResponse, error)
	AnswerQuestions(ctx context.Context, in *AnswerQuestionsRequest, opts ...grpc.CallOption) (*AnswerQuestionsResponse, error)
	StartRandomQuiz(ctx context.Context, in *StartRandomQuizRequest, opts ...grpc.CallOption) (*StartQuizResponse, error)
	StartGenreQuiz(ctx context.Context, in *StartGenreQuizRequest, opts ...grpc.CallOption) (*StartQuizResponse, error)
	StartForYouQuiz(ctx context.Context, in *StartForYouQuizRequest, opts ...grpc.CallOption) (*StartQuizResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetQuizzes(ctx context.Context, in *GetQuizzesRequest, opts ...grpc.CallOption) (*GetQuizzesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuizzesResponse)
	err := c.cc.Invoke(ctx, GameService_GetQuizzes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionsResponse)
	err := c.cc.Invoke(ctx, GameService_GetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) JoinQuiz(ctx context.Context, in *JoinQuizRequest, opts ...grpc.CallOption) (*JoinQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinQuizResponse)
	err := c.cc.Invoke(ctx, GameService_JoinQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) QuitQuiz(ctx context.Context, in *QuitQuizRequest, opts ...grpc.CallOption) (*QuitQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuitQuizResponse)
	err := c.cc.Invoke(ctx, GameService_QuitQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreateQuiz(ctx context.Context, in *CreateQuizRequest, opts ...grpc.CallOption) (*CreateQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuizResponse)
	err := c.cc.Invoke(ctx, GameService_CreateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetActiveQuiz(ctx context.Context, in *GetActiveQuizRequest, opts ...grpc.CallOption) (*GetActiveQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveQuizResponse)
	err := c.cc.Invoke(ctx, GameService_GetActiveQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AnswerQuestions(ctx context.Context, in *AnswerQuestionsRequest, opts ...grpc.CallOption) (*AnswerQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerQuestionsResponse)
	err := c.cc.Invoke(ctx, GameService_AnswerQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) StartRandomQuiz(ctx context.Context, in *StartRandomQuizRequest, opts ...grpc.CallOption) (*StartQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartQuizResponse)
	err := c.cc.Invoke(ctx, GameService_StartRandomQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) StartGenreQuiz(ctx context.Context, in *StartGenreQuizRequest, opts ...grpc.CallOption) (*StartQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartQuizResponse)
	err := c.cc.Invoke(ctx, GameService_StartGenreQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) StartForYouQuiz(ctx context.Context, in *StartForYouQuizRequest, opts ...grpc.CallOption) (*StartQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartQuizResponse)
	err := c.cc.Invoke(ctx, GameService_StartForYouQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	GetQuizzes(context.Context, *GetQuizzesRequest) (*GetQuizzesResponse, error)
	GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error)
	JoinQuiz(context.Context, *JoinQuizRequest) (*JoinQuizResponse, error)
	QuitQuiz(context.Context, *QuitQuizRequest) (*QuitQuizResponse, error)
	CreateQuiz(context.Context, *CreateQuizRequest) (*CreateQuizResponse, error)
	GetActiveQuiz(context.Context, *GetActiveQuizRequest) (*GetActiveQuizResponse, error)
	AnswerQuestions(context.Context, *AnswerQuestionsRequest) (*AnswerQuestionsResponse, error)
	StartRandomQuiz(context.Context, *StartRandomQuizRequest) (*StartQuizResponse, error)
	StartGenreQuiz(context.Context, *StartGenreQuizRequest) (*StartQuizResponse, error)
	StartForYouQuiz(context.Context, *StartForYouQuizRequest) (*StartQuizResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetQuizzes(context.Context, *GetQuizzesRequest) (*GetQuizzesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuizzes not implemented")
}
func (UnimplementedGameServiceServer) GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedGameServiceServer) JoinQuiz(context.Context, *JoinQuizRequest) (*JoinQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinQuiz not implemented")
}
func (UnimplementedGameServiceServer) QuitQuiz(context.Context, *QuitQuizRequest) (*QuitQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuitQuiz not implemented")
}
func (UnimplementedGameServiceServer) CreateQuiz(context.Context, *CreateQuizRequest) (*CreateQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuiz not implemented")
}
func (UnimplementedGameServiceServer) GetActiveQuiz(context.Context, *GetActiveQuizRequest) (*GetActiveQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveQuiz not implemented")
}
func (UnimplementedGameServiceServer) AnswerQuestions(context.Context, *AnswerQuestionsRequest) (*AnswerQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerQuestions not implemented")
}
func (UnimplementedGameServiceServer) StartRandomQuiz(context.Context, *StartRandomQuizRequest) (*StartQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRandomQuiz not implemented")
}
func (UnimplementedGameServiceServer) StartGenreQuiz(context.Context, *StartGenreQuizRequest) (*StartQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGenreQuiz not implemented")
}
func (UnimplementedGameServiceServer) StartForYouQuiz(context.Context, *StartForYouQuizRequest) (*StartQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartForYouQuiz not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetQuizzes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizzesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetQuizzes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetQuizzes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetQuizzes(ctx, req.(*GetQuizzesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetSessions(ctx, req.(*GetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_JoinQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).JoinQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_JoinQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).JoinQuiz(ctx, req.(*JoinQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_QuitQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).QuitQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_QuitQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).QuitQuiz(ctx, req.(*QuitQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_CreateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateQuiz(ctx, req.(*CreateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetActiveQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetActiveQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetActiveQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetActiveQuiz(ctx, req.(*GetActiveQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AnswerQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AnswerQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AnswerQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AnswerQuestions(ctx, req.(*AnswerQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_StartRandomQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRandomQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StartRandomQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_StartRandomQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StartRandomQuiz(ctx, req.(*StartRandomQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_StartGenreQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGenreQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StartGenreQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_StartGenreQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StartGenreQuiz(ctx, req.(*StartGenreQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_StartForYouQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartForYouQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StartForYouQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_StartForYouQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StartForYouQuiz(ctx, req.(*StartForYouQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuizzes",
			Handler:    _GameService_GetQuizzes_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _GameService_GetSessions_Handler,
		},
		{
			MethodName: "JoinQuiz",
			Handler:    _GameService_JoinQuiz_Handler,
		},
		{
			MethodName: "QuitQuiz",
			Handler:    _GameService_QuitQuiz_Handler,
		},
		{
			MethodName: "CreateQuiz",
			Handler:    _GameService_CreateQuiz_Handler,
		},
		{
			MethodName: "GetActiveQuiz",
			Handler:    _GameService_GetActiveQuiz_Handler,
		},
		{
			MethodName: "AnswerQuestions",
			Handler:    _GameService_AnswerQuestions_Handler,
		},
		{
			MethodName: "StartRandomQuiz",
			Handler:    _GameService_StartRandomQuiz_Handler,
		},
		{
			MethodName: "StartGenreQuiz",
			Handler:    _GameService_StartGenreQuiz_Handler,
		},
		{
			MethodName: "StartForYouQuiz",
			Handler:    _GameService_StartForYouQuiz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/game.proto",
}
