syntax = "proto3";

package user.v1;
option go_package = "github.com/BOURREAUQuentin/game/api/proto/v1";

import "google/protobuf/timestamp.proto";

service GameService {
  rpc GetQuizzes (GetQuizzesRequest) returns (GetQuizzesResponse);
  rpc GetSessions (GetSessionsRequest) returns (GetSessionsResponse);
}

message GetQuizzesRequest {

}

message GetQuizzesResponse {
  repeated Quiz quizzes = 1;
}

message GetSessionsRequest {

}

message GetSessionsResponse {
  repeated Session sessions = 1;
}

message Session {
  string id = 1;
  string user_id = 2;
  string quiz_id = 3;
  google.protobuf.Timestamp joined_at = 4;
  google.protobuf.Timestamp last_activity = 5;
}

message Quiz {
  string id = 1;
  string title = 2;
  string type = 3;       // 'simple', 'personalise', etc.
  string creator_id = 4;
  string status = 5;
  google.protobuf.Timestamp created_at = 6;
  repeated Question questions = 7;
}

message Question {
  string question_id = 1;
  string text = 2;
}