// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/v1/game.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRandomQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRandomQuizRequest) Reset() {
	*x = StartRandomQuizRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRandomQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRandomQuizRequest) ProtoMessage() {}

func (x *StartRandomQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRandomQuizRequest.ProtoReflect.Descriptor instead.
func (*StartRandomQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *StartRandomQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StartGenreQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGenreQuizRequest) Reset() {
	*x = StartGenreQuizRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGenreQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGenreQuizRequest) ProtoMessage() {}

func (x *StartGenreQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGenreQuizRequest.ProtoReflect.Descriptor instead.
func (*StartGenreQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *StartGenreQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartGenreQuizRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type StartQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartQuizResponse) Reset() {
	*x = StartQuizResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQuizResponse) ProtoMessage() {}

func (x *StartQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQuizResponse.ProtoReflect.Descriptor instead.
func (*StartQuizResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *StartQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type GetQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesRequest) Reset() {
	*x = GetQuizzesRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesRequest) ProtoMessage() {}

func (x *GetQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesRequest.ProtoReflect.Descriptor instead.
func (*GetQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{3}
}

type GetQuizzesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*Quiz                `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesResponse) Reset() {
	*x = GetQuizzesResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesResponse) ProtoMessage() {}

func (x *GetQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesResponse.ProtoReflect.Descriptor instead.
func (*GetQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuizzesResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

type AnswerQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Answers       []int32                `protobuf:"varint,2,rep,packed,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionsRequest) Reset() {
	*x = AnswerQuestionsRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionsRequest) ProtoMessage() {}

func (x *AnswerQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionsRequest.ProtoReflect.Descriptor instead.
func (*AnswerQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerQuestionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnswerQuestionsRequest) GetAnswers() []int32 {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AnswerQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Results       []*QuestionResult      `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionsResponse) Reset() {
	*x = AnswerQuestionsResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionsResponse) ProtoMessage() {}

func (x *AnswerQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionsResponse.ProtoReflect.Descriptor instead.
func (*AnswerQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerQuestionsResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnswerQuestionsResponse) GetResults() []*QuestionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type QuestionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QuestionId         string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	IsCorrect          bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	CorrectAnswerIndex int32                  `protobuf:"varint,3,opt,name=correct_answer_index,json=correctAnswerIndex,proto3" json:"correct_answer_index,omitempty"`
	UserAnswerIndex    int32                  `protobuf:"varint,4,opt,name=user_answer_index,json=userAnswerIndex,proto3" json:"user_answer_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuestionResult) Reset() {
	*x = QuestionResult{}
	mi := &file_api_proto_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResult) ProtoMessage() {}

func (x *QuestionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResult.ProtoReflect.Descriptor instead.
func (*QuestionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionResult) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuestionResult) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuestionResult) GetCorrectAnswerIndex() int32 {
	if x != nil {
		return x.CorrectAnswerIndex
	}
	return 0
}

func (x *QuestionResult) GetUserAnswerIndex() int32 {
	if x != nil {
		return x.UserAnswerIndex
	}
	return 0
}

type GetActiveQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveQuizRequest) Reset() {
	*x = GetActiveQuizRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveQuizRequest) ProtoMessage() {}

func (x *GetActiveQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveQuizRequest.ProtoReflect.Descriptor instead.
func (*GetActiveQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *GetActiveQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetActiveQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveQuizResponse) Reset() {
	*x = GetActiveQuizResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveQuizResponse) ProtoMessage() {}

func (x *GetActiveQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveQuizResponse.ProtoReflect.Descriptor instead.
func (*GetActiveQuizResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *GetActiveQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type CreateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreatorId     string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Questions     []*Question            `protobuf:"bytes,4,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *CreateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuizRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQuizRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateQuizRequest) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CreateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizResponse) Reset() {
	*x = CreateQuizResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizResponse) ProtoMessage() {}

func (x *CreateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizResponse.ProtoReflect.Descriptor instead.
func (*CreateQuizResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *CreateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{12}
}

type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type JoinQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQuizRequest) Reset() {
	*x = JoinQuizRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQuizRequest) ProtoMessage() {}

func (x *JoinQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQuizRequest.ProtoReflect.Descriptor instead.
func (*JoinQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *JoinQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinQuizRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type JoinQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQuizResponse) Reset() {
	*x = JoinQuizResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQuizResponse) ProtoMessage() {}

func (x *JoinQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQuizResponse.ProtoReflect.Descriptor instead.
func (*JoinQuizResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *JoinQuizResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type QuitQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitQuizRequest) Reset() {
	*x = QuitQuizRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitQuizRequest) ProtoMessage() {}

func (x *QuitQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitQuizRequest.ProtoReflect.Descriptor instead.
func (*QuitQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *QuitQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuitQuizRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type QuitQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitQuizResponse) Reset() {
	*x = QuitQuizResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitQuizResponse) ProtoMessage() {}

func (x *QuitQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitQuizResponse.ProtoReflect.Descriptor instead.
func (*QuitQuizResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *QuitQuizResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,3,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_v1_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *Session) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Session) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // 'simple', 'personalise', etc.
	CreatorId     string                 `protobuf:"bytes,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Questions     []*Question            `protobuf:"bytes,6,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_api_proto_v1_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{19}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quiz) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Quiz) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Quiz) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Quiz) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QuestionId         string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text               string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Choices            []string               `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	CorrectAnswerIndex int32                  `protobuf:"varint,4,opt,name=correct_answer_index,json=correctAnswerIndex,proto3" json:"correct_answer_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_api_proto_v1_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{20}
}

func (x *Question) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *Question) GetCorrectAnswerIndex() int32 {
	if x != nil {
		return x.CorrectAnswerIndex
	}
	return 0
}

var File_api_proto_v1_game_proto protoreflect.FileDescriptor

const file_api_proto_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/game.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x16StartRandomQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x15StartGenreQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genre\"6\n" +
	"\x11StartQuizResponse\x12!\n" +
	"\x04quiz\x18\x01 \x01(\v2\r.user.v1.QuizR\x04quiz\"\x13\n" +
	"\x11GetQuizzesRequest\"=\n" +
	"\x12GetQuizzesResponse\x12'\n" +
	"\aquizzes\x18\x01 \x03(\v2\r.user.v1.QuizR\aquizzes\"K\n" +
	"\x16AnswerQuestionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aanswers\x18\x02 \x03(\x05R\aanswers\"b\n" +
	"\x17AnswerQuestionsResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.user.v1.QuestionResultR\aresults\"\xae\x01\n" +
	"\x0eQuestionResult\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x120\n" +
	"\x14correct_answer_index\x18\x03 \x01(\x05R\x12correctAnswerIndex\x12*\n" +
	"\x11user_answer_index\x18\x04 \x01(\x05R\x0fuserAnswerIndex\"/\n" +
	"\x14GetActiveQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x15GetActiveQuizResponse\x12!\n" +
	"\x04quiz\x18\x01 \x01(\v2\r.user.v1.QuizR\x04quiz\"\x8d\x01\n" +
	"\x11CreateQuizRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12/\n" +
	"\tquestions\x18\x04 \x03(\v2\x11.user.v1.QuestionR\tquestions\"7\n" +
	"\x12CreateQuizResponse\x12!\n" +
	"\x04quiz\x18\x01 \x01(\v2\r.user.v1.QuizR\x04quiz\"\x14\n" +
	"\x12GetSessionsRequest\"C\n" +
	"\x13GetSessionsResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.user.v1.SessionR\bsessions\"C\n" +
	"\x0fJoinQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\">\n" +
	"\x10JoinQuizResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.user.v1.SessionR\asession\"C\n" +
	"\x0fQuitQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\",\n" +
	"\x10QuitQuizResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc5\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x03 \x01(\tR\x06quizId\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12?\n" +
	"\rlast_activity\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\xcb\x01\n" +
	"\x04Quiz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\tR\tcreatorId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12/\n" +
	"\tquestions\x18\x06 \x03(\v2\x11.user.v1.QuestionR\tquestions\"\x8b\x01\n" +
	"\bQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\achoices\x18\x03 \x03(\tR\achoices\x120\n" +
	"\x14correct_answer_index\x18\x04 \x01(\x05R\x12correctAnswerIndex2\xab\x05\n" +
	"\vGameService\x12E\n" +
	"\n" +
	"GetQuizzes\x12\x1a.user.v1.GetQuizzesRequest\x1a\x1b.user.v1.GetQuizzesResponse\x12H\n" +
	"\vGetSessions\x12\x1b.user.v1.GetSessionsRequest\x1a\x1c.user.v1.GetSessionsResponse\x12?\n" +
	"\bJoinQuiz\x12\x18.user.v1.JoinQuizRequest\x1a\x19.user.v1.JoinQuizResponse\x12?\n" +
	"\bQuitQuiz\x12\x18.user.v1.QuitQuizRequest\x1a\x19.user.v1.QuitQuizResponse\x12E\n" +
	"\n" +
	"CreateQuiz\x12\x1a.user.v1.CreateQuizRequest\x1a\x1b.user.v1.CreateQuizResponse\x12N\n" +
	"\rGetActiveQuiz\x12\x1d.user.v1.GetActiveQuizRequest\x1a\x1e.user.v1.GetActiveQuizResponse\x12T\n" +
	"\x0fAnswerQuestions\x12\x1f.user.v1.AnswerQuestionsRequest\x1a .user.v1.AnswerQuestionsResponse\x12N\n" +
	"\x0fStartRandomQuiz\x12\x1f.user.v1.StartRandomQuizRequest\x1a\x1a.user.v1.StartQuizResponse\x12L\n" +
	"\x0eStartGenreQuiz\x12\x1e.user.v1.StartGenreQuizRequest\x1a\x1a.user.v1.StartQuizResponseB.Z,github.com/BOURREAUQuentin/game/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_game_proto_rawDescOnce sync.Once
	file_api_proto_v1_game_proto_rawDescData []byte
)

func file_api_proto_v1_game_proto_rawDescGZIP() []byte {
	file_api_proto_v1_game_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_game_proto_rawDesc), len(file_api_proto_v1_game_proto_rawDesc)))
	})
	return file_api_proto_v1_game_proto_rawDescData
}

var file_api_proto_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_v1_game_proto_goTypes = []any{
	(*StartRandomQuizRequest)(nil),  // 0: user.v1.StartRandomQuizRequest
	(*StartGenreQuizRequest)(nil),   // 1: user.v1.StartGenreQuizRequest
	(*StartQuizResponse)(nil),       // 2: user.v1.StartQuizResponse
	(*GetQuizzesRequest)(nil),       // 3: user.v1.GetQuizzesRequest
	(*GetQuizzesResponse)(nil),      // 4: user.v1.GetQuizzesResponse
	(*AnswerQuestionsRequest)(nil),  // 5: user.v1.AnswerQuestionsRequest
	(*AnswerQuestionsResponse)(nil), // 6: user.v1.AnswerQuestionsResponse
	(*QuestionResult)(nil),          // 7: user.v1.QuestionResult
	(*GetActiveQuizRequest)(nil),    // 8: user.v1.GetActiveQuizRequest
	(*GetActiveQuizResponse)(nil),   // 9: user.v1.GetActiveQuizResponse
	(*CreateQuizRequest)(nil),       // 10: user.v1.CreateQuizRequest
	(*CreateQuizResponse)(nil),      // 11: user.v1.CreateQuizResponse
	(*GetSessionsRequest)(nil),      // 12: user.v1.GetSessionsRequest
	(*GetSessionsResponse)(nil),     // 13: user.v1.GetSessionsResponse
	(*JoinQuizRequest)(nil),         // 14: user.v1.JoinQuizRequest
	(*JoinQuizResponse)(nil),        // 15: user.v1.JoinQuizResponse
	(*QuitQuizRequest)(nil),         // 16: user.v1.QuitQuizRequest
	(*QuitQuizResponse)(nil),        // 17: user.v1.QuitQuizResponse
	(*Session)(nil),                 // 18: user.v1.Session
	(*Quiz)(nil),                    // 19: user.v1.Quiz
	(*Question)(nil),                // 20: user.v1.Question
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_api_proto_v1_game_proto_depIdxs = []int32{
	19, // 0: user.v1.StartQuizResponse.quiz:type_name -> user.v1.Quiz
	19, // 1: user.v1.GetQuizzesResponse.quizzes:type_name -> user.v1.Quiz
	7,  // 2: user.v1.AnswerQuestionsResponse.results:type_name -> user.v1.QuestionResult
	19, // 3: user.v1.GetActiveQuizResponse.quiz:type_name -> user.v1.Quiz
	20, // 4: user.v1.CreateQuizRequest.questions:type_name -> user.v1.Question
	19, // 5: user.v1.CreateQuizResponse.quiz:type_name -> user.v1.Quiz
	18, // 6: user.v1.GetSessionsResponse.sessions:type_name -> user.v1.Session
	18, // 7: user.v1.JoinQuizResponse.session:type_name -> user.v1.Session
	21, // 8: user.v1.Session.joined_at:type_name -> google.protobuf.Timestamp
	21, // 9: user.v1.Session.last_activity:type_name -> google.protobuf.Timestamp
	21, // 10: user.v1.Quiz.created_at:type_name -> google.protobuf.Timestamp
	20, // 11: user.v1.Quiz.questions:type_name -> user.v1.Question
	3,  // 12: user.v1.GameService.GetQuizzes:input_type -> user.v1.GetQuizzesRequest
	12, // 13: user.v1.GameService.GetSessions:input_type -> user.v1.GetSessionsRequest
	14, // 14: user.v1.GameService.JoinQuiz:input_type -> user.v1.JoinQuizRequest
	16, // 15: user.v1.GameService.QuitQuiz:input_type -> user.v1.QuitQuizRequest
	10, // 16: user.v1.GameService.CreateQuiz:input_type -> user.v1.CreateQuizRequest
	8,  // 17: user.v1.GameService.GetActiveQuiz:input_type -> user.v1.GetActiveQuizRequest
	5,  // 18: user.v1.GameService.AnswerQuestions:input_type -> user.v1.AnswerQuestionsRequest
	0,  // 19: user.v1.GameService.StartRandomQuiz:input_type -> user.v1.StartRandomQuizRequest
	1,  // 20: user.v1.GameService.StartGenreQuiz:input_type -> user.v1.StartGenreQuizRequest
	4,  // 21: user.v1.GameService.GetQuizzes:output_type -> user.v1.GetQuizzesResponse
	13, // 22: user.v1.GameService.GetSessions:output_type -> user.v1.GetSessionsResponse
	15, // 23: user.v1.GameService.JoinQuiz:output_type -> user.v1.JoinQuizResponse
	17, // 24: user.v1.GameService.QuitQuiz:output_type -> user.v1.QuitQuizResponse
	11, // 25: user.v1.GameService.CreateQuiz:output_type -> user.v1.CreateQuizResponse
	9,  // 26: user.v1.GameService.GetActiveQuiz:output_type -> user.v1.GetActiveQuizResponse
	6,  // 27: user.v1.GameService.AnswerQuestions:output_type -> user.v1.AnswerQuestionsResponse
	2,  // 28: user.v1.GameService.StartRandomQuiz:output_type -> user.v1.StartQuizResponse
	2,  // 29: user.v1.GameService.StartGenreQuiz:output_type -> user.v1.StartQuizResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_v1_game_proto_init() }
func file_api_proto_v1_game_proto_init() {
	if File_api_proto_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_game_proto_rawDesc), len(file_api_proto_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_game_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_game_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_game_proto_msgTypes,
	}.Build()
	File_api_proto_v1_game_proto = out.File
	file_api_proto_v1_game_proto_goTypes = nil
	file_api_proto_v1_game_proto_depIdxs = nil
}
