// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/v1/game.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesRequest) Reset() {
	*x = GetQuizzesRequest{}
	mi := &file_api_proto_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesRequest) ProtoMessage() {}

func (x *GetQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesRequest.ProtoReflect.Descriptor instead.
func (*GetQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{0}
}

type GetQuizzesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*Quiz                `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesResponse) Reset() {
	*x = GetQuizzesResponse{}
	mi := &file_api_proto_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesResponse) ProtoMessage() {}

func (x *GetQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesResponse.ProtoReflect.Descriptor instead.
func (*GetQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuizzesResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // 'simple', 'personalise', etc.
	CreatorId     string                 `protobuf:"bytes,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Questions     []*Question            `protobuf:"bytes,7,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_api_proto_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quiz) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Quiz) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Quiz) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Quiz) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Quiz) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_api_proto_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_api_proto_v1_game_proto protoreflect.FileDescriptor

const file_api_proto_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/game.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11GetQuizzesRequest\"=\n" +
	"\x12GetQuizzesResponse\x12'\n" +
	"\aquizzes\x18\x01 \x03(\v2\r.user.v1.QuizR\aquizzes\"\xe3\x01\n" +
	"\x04Quiz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\tR\tcreatorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12/\n" +
	"\tquestions\x18\a \x03(\v2\x11.user.v1.QuestionR\tquestions\"?\n" +
	"\bQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text2T\n" +
	"\vGameService\x12E\n" +
	"\n" +
	"GetQuizzes\x12\x1a.user.v1.GetQuizzesRequest\x1a\x1b.user.v1.GetQuizzesResponseB.Z,github.com/BOURREAUQuentin/game/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_game_proto_rawDescOnce sync.Once
	file_api_proto_v1_game_proto_rawDescData []byte
)

func file_api_proto_v1_game_proto_rawDescGZIP() []byte {
	file_api_proto_v1_game_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_game_proto_rawDesc), len(file_api_proto_v1_game_proto_rawDesc)))
	})
	return file_api_proto_v1_game_proto_rawDescData
}

var file_api_proto_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_game_proto_goTypes = []any{
	(*GetQuizzesRequest)(nil),     // 0: user.v1.GetQuizzesRequest
	(*GetQuizzesResponse)(nil),    // 1: user.v1.GetQuizzesResponse
	(*Quiz)(nil),                  // 2: user.v1.Quiz
	(*Question)(nil),              // 3: user.v1.Question
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_proto_v1_game_proto_depIdxs = []int32{
	2, // 0: user.v1.GetQuizzesResponse.quizzes:type_name -> user.v1.Quiz
	4, // 1: user.v1.Quiz.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: user.v1.Quiz.questions:type_name -> user.v1.Question
	0, // 3: user.v1.GameService.GetQuizzes:input_type -> user.v1.GetQuizzesRequest
	1, // 4: user.v1.GameService.GetQuizzes:output_type -> user.v1.GetQuizzesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_game_proto_init() }
func file_api_proto_v1_game_proto_init() {
	if File_api_proto_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_game_proto_rawDesc), len(file_api_proto_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_game_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_game_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_game_proto_msgTypes,
	}.Build()
	File_api_proto_v1_game_proto = out.File
	file_api_proto_v1_game_proto_goTypes = nil
	file_api_proto_v1_game_proto_depIdxs = nil
}
