services:
  catalog:
    build: 
      context: .
      dockerfile: catalog/Dockerfile
    ports: 
    - 3200:3200
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/catalog_db?authSource=admin

  mongo:
    image: mongo
    restart: always
    ports: 
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./catalog/import/init-data.js:/docker-entrypoint-initdb.d/init-data.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  game:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game_service
    ports:
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/game_db?authSource=admin
    depends_on:
      - mongo

  gateway:
    build: ./gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - game
